name: test 

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: magnus
          POSTGRES_PASSWORD: bong-cloud
          POSTGRES_DB: chess-league
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: "20"

      - name: Setup pnpm
        run: npm i -g pnpm@10

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: true

      - name: Test
        shell: bash
        env:
          FUZZTIME: 5m
        run: make fuzz -j

